import { api } from "@/utils/api";
import Head from "next/head";

export default function Home() {
  const { data: books } = api.book.getAll.useQuery();
  const { data: users } = api.user.getAll.useQuery();

  console.log({ books });
  console.log({ users });

  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Books</span> App
          </h1>
          <p className="text-2xl text-white">
            {books ? books.map(b => (<div>{b.name}</div>)) : "Loading..."}
          </p>
        </div>
      </main>
    </>
  );
}
